### ISSUE TITLE
Issue with importing ConsoleHandler from logalpha

### ISSUE THREAD

**Issue by IlsaCooke** [glentner/dataphile#1]
Hi,

I'm having issues with running dataphile. I tried to run:

from dataphile.datasets import SyntheticDataset
from dataphile.statistics.distributions import polynomial1D

xdata, ydata = SyntheticDataset(polynomial1D, [100, -0.01, -1e-5], (0, 2400), linspace=True,
                                noise=0, samples=2400).generate()

I get the following error:

ImportError: cannot import name 'ConsoleHandler' from 'logalpha' (C:\anaconda\lib\site-packages\logalpha\__init__.py)

I've tried to reinstall logalpha but the error persists.
I'm using python 3.7 in Anaconda

Thanks for your help!

**Comment by glentner** [comment]
When I first wrote the setup.py for _dataphile_ I didn't specify version numbers unfortunately and _logalpha_ is now in version 2 which broke the API for _dataphile_. I'll try to fix this soon so others don't have the same issue. For now, try:

```
pip install --upgrade 'logalpha<2'
```

**Comment by glentner** [comment]
I pushed some fixes last night that should make things behavior better in the future.

**Comment by IlsaCooke** [comment]
Thank you! It's working great.
